version: "3.8"

services:

  app-rm565824:

    build: .

    container_name: app-rm565824

    restart: always

    ports:
      - "8080:8080"

    environment:
      USER_DB_ORACLE: system
      PASSWORD_DB_ORACLE: Oracle123

    depends_on:
      - oracle-rm565824

    networks:
      - astro-network

  oracle-rm565824:

    image: gvenzl/oracle-free:latest

    container_name: oracle-rm565824

    restart: always

    ports:
      - "1522:1521"

    environment:
      ORACLE_PASSWORD: Oracle123

    volumes:
      - oracle_data:/opt/oracle/oradata

    networks:
      - astro-network

volumes:

  oracle_data:

networks:

  astro-network:
    driver: bridge