services:

  oracle-rm565824:
    image: gvenzl/oracle-free:latest
    container_name: oracle-rm565824
    restart: always

    ports:
      - "1522:1521"

    environment:
      ORACLE_PASSWORD: 120306

    volumes:
      - oracle_data:/opt/oracle/oradata

    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

    networks:
      - astro-network

  app-rm565824:
    build: .
    container_name: app-rm565824
    restart: always

    depends_on:
      oracle-rm565824:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      USER_DB_ORACLE: system
      PASSWORD_DB_ORACLE: 120306

    networks:
      - astro-network

volumes:
  oracle_data:

networks:
  astro-network:
    driver: bridge