spring.application.name=javaspg

spring.datasource.url=jdbc:oracle:thin:@oracle-rm565824:1521/FREEPDB1
spring.datasource.username=${USER_DB_ORACLE:system}
spring.datasource.password=${PASSWORD_DB_ORACLE:120306}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect